version: '3'

services:
  # db:
  #   image: mysql:5.7
  #   container_name: mysql
  #   ports:
  #     - '3306:3306'
  #   environment:
  #     MYSQL_DATABASE: 'jobs_data'
  #     MYSQL_USER: 'root'
  #     MYSQL_PASSWORD: 'django'
  #     MYSQL_ROOT_PASSWORD: 'django'
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: app
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    # depends_on:
    #   - db