# Generated by Django 3.0.7 on 2020-06-29 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0004_auto_20200628_2157'),
        ('caixa', '0003_auto_20200628_1916'),
    ]

    operations = [
    ]
