# Generated by Django 3.0.7 on 2020-06-28 15:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('cd_Caixa', models.AutoField(primary_key=True, serialize=False)),
                ('vl_CaixaInicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vl_Dinheiro', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vl_CartaoCredito', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vl_CartaoDebito', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vl_Refeicao', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vl_Online', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vl_Sangrias', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vl_Despesas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vl_Entradas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vl_Faturamento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='ControleCaixa',
            fields=[
                ('cd_ControleCaixa', models.AutoField(primary_key=True, serialize=False)),
                ('dt_AberturaCaixa', models.DateTimeField(default=django.utils.timezone.now)),
                ('dt_FechamentoCaixa', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DespesaTipo',
            fields=[
                ('cd_DespesaTipo', models.AutoField(primary_key=True, serialize=False)),
                ('ds_DespesaTipo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('cd_Despesa', models.AutoField(primary_key=True, serialize=False)),
                ('vl_Despesa', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cd_Caixa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='caixa.Caixa')),
                ('cd_DespesaTipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='caixa.DespesaTipo')),
            ],
        ),
        migrations.CreateModel(
            name='CaixaSangria',
            fields=[
                ('cd_Sangria', models.AutoField(primary_key=True, serialize=False)),
                ('vl_Sangria', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cd_Caixa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='caixa.Caixa')),
            ],
        ),
        migrations.CreateModel(
            name='CaixaEntrada',
            fields=[
                ('cd_Entrada', models.AutoField(primary_key=True, serialize=False)),
                ('vl_Entrada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cd_Caixa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='caixa.Caixa')),
            ],
        ),
        migrations.AddField(
            model_name='caixa',
            name='cd_ControleCaixa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='caixa.ControleCaixa'),
        ),
    ]
