# Generated by Django 3.0.7 on 2020-06-28 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Despesas',
            new_name='Despesa',
        ),
        migrations.RenameModel(
            old_name='CaixaSangria',
            new_name='Entrada',
        ),
        migrations.RenameModel(
            old_name='CaixaEntrada',
            new_name='Sangria',
        ),
        migrations.RenameField(
            model_name='entrada',
            old_name='cd_Sangria',
            new_name='cd_Entrada',
        ),
        migrations.RenameField(
            model_name='entrada',
            old_name='vl_Sangria',
            new_name='vl_Entrada',
        ),
        migrations.RenameField(
            model_name='sangria',
            old_name='cd_Entrada',
            new_name='cd_Sangria',
        ),
        migrations.RenameField(
            model_name='sangria',
            old_name='vl_Entrada',
            new_name='vl_Sangria',
        ),
    ]
