# Generated by Django 3.0.7 on 2020-06-28 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0002_auto_20200628_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='cd_ControleCaixa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='caixa.ControleCaixa', unique=True),
        ),
        migrations.AlterField(
            model_name='controlecaixa',
            name='dt_AberturaCaixa',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='controlecaixa',
            name='dt_FechamentoCaixa',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
