# Generated by Django 3.0.7 on 2020-06-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0002_auto_20200628_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlecaixa',
            name='dt_AberturaCaixa',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='controlecaixa',
            name='dt_FechamentoCaixa',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
