# Generated by Django 3.0.7 on 2020-06-29 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0003_auto_20200628_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='cd_ControleCaixa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='caixa.ControleCaixa'),
        ),
        migrations.AlterField(
            model_name='controlecaixa',
            name='dt_FechamentoCaixa',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
